import type { CustomMarker } from '~/types/CustomMarker';

export const markers: CustomMarker[] = [
  {
    lat: 52.496593,
    lng: 13.437449,
    title: 'Görli.',
    description: '<p>Nicht sprechen</p>',
    creatorIds: ['bjoern'],
  },
  {
    lat: 52.534464,
    lng: 13.404775,
    title: 'Macke Prinz',
    description:
      '<p>Berlin hat nur diese eine Bar, oder? Und auch nur diesen einen Corner-Spot, richtig? Es wäre ja auch Wahnsinn, sich mal weiter raus zu trauen.</p>',
    creatorIds: ['bjoern'],
    link: 'https://maps.app.goo.gl/5hqfxYapdYM1wB2D8',
  },
  {
    lat: 54.332541,
    lng: 10.110881,
    title: 'Bex & Mareikes Hochzeit',
    description:
      '<p>Schön war das hier! Vor allem die Location und die veganen Würstchen, die wirklich erstaunlich nach Fleisch schmeckten. Also fast so, als wäre da Fleisch drin. Krass, was alles möglich ist in der heutigen Zeit.</p>',
    link: 'https://maps.app.goo.gl/KhL4xPdf1hzPAkwL7',
    creatorIds: ['bjoern'],
  },
  {
    lat: 47.001782,
    lng: 11.506068,
    title: 'Outside!!!',
    description: `<p>"Outside" auf voller Lautstärke und dazu die Oliven auf dem Armaturenbrett. Ich bin mir nicht mehr ganz sicher auf welcher Autobahn das war, glaube aber, kurz vor irgendeiner Grenze, ich nehme einfach mal den Brennerpass.</p>
      <p>Der Marker hier steht natürlich auch stellvertretend für unseren ganzen Italien-Trip. Ich sag nur: Nachtwanderungen, Strafzettel, explodierende Feuerzeuge, Assassin's Creed, Wein ohne Korkenzieher, irgendwo im Nichts in ner Kurve pennen und tagelang nicht duschen - la dolce vita eben.</p>`,
    creatorIds: ['bjoern'],
  },
  {
    lat: 47.191444,
    lng: 8.395674,
    title: 'Sins',
    description:
      '<p>Läääät, diese Gemeinde in der Schweiz heißt wirklich Sins! Sins! Hat Britta ausfindig gemacht. Und jetzt 40.000 Liegestütze. Kleiner Pisser.</p>',
    creatorIds: ['bjoern'],
  },
  {
    lat: 41.836683630751736,
    lng: 6.793894236512097,
    title: 'Ich will nicht nüchtern sterben! 💊',
    description: '<p>Irgendwo hier muss die Naomi gesunken und der Heli ins Wasser gekracht sein. Aber die Frage bleibt ja: Wo sind die Ludes?!</p>',
    creatorIds: ['bjoern'],
  },
  {
    lat: 53.170273,
    lng: 13.579556,
    title: 'Unsere Unterkunft an deinem 30sten!',
    description:
      '<p>Zu dem Zeitpunkt, wo ich das hier schreibe, waren wir zwar noch nicht da, aber ich hoffe einfach mal, hier entstehen ein paar ganz tolle Erinnerungen!</p>',
    creatorIds: ['bjoern'],
    link: 'https://www.airbnb.de/rooms/1099297141890162705?guests=1&adults=1&s=67&unique_share_id=7ef88f05-1ab9-4531-bd8f-5eb847773caa',
  },
  {
    lat: 53.595965,
    lng: 10.041669,
    title: 'Wasmannstraße 13',
    description: [
      {
        creatorId: 'bjoern',
        title: 'Unsere Bude ❤️',
        content:
          '<p>The one and only. Verrückte, tolle, wichtige Zeit! Irgendwie kaum zu glauben, dass jetzt keiner mehr von uns auf der Ecke da wohnt. Außer natürlich Manni!</p>',
      },
      {
        creatorId: 'laura',
        title: 'Chaos WG Münker Wegener',
        content:
          '<p>Lax und Lax, verschieden und doch ein Paar, ziehen zusammen und die Clique ist da.Ob zu „König der Löwen“ gröhlend, am Klavier, oder im Leder-Outfit, die Nachbarn loben Sie noch dafür!</p>',
      },
    ],
    creatorIds: ['bjoern', 'laura'],
  },
  {
    lat: 53.57149,
    lng: 9.976417,
    title: 'Schlumpis',
    description: [
      {
        creatorId: 'bjoern',
        content:
          '<p>Absolute Frechheit, Lax und meine WG als Chaos-WG zu bezeichnen, Laura !!111!. Wer im Glashaus sitzt, sollte lieber im Keller bumsen! Aber zugegeben, schön ist es hier, egal ob beim CSD, Halloween, Geburtstagen, einfach nur zum Frühstücken oder Zocken.</p>',
      },
      {
        creatorId: 'laura',
        content: '<p>Nur auf ein Getränk? Das blieb nie dabei! Küchentanz, Deeptalk und viel Trinkerei!</p>',
      },
      {
        creatorId: 'sophia',
        content: '<p>No words needed! 10000 Erinnerungen</p>',
      },
    ],
    creatorIds: ['bjoern', 'laura', 'sophia'],
  },
  {
    lat: 53.620577,
    lng: 9.86355,
    title: 'TV-AG Raum',
    description: [
      {
        creatorId: 'bjoern',
        content: `<p>Gurke!!! Und natürlich steht der Marker irgendwie auch für unsere Zeit am WoBo ingesamt. Kann man sowieso nicht in Wort fassen. Fest steht: Bestes Schulpärchen ever ❤️</p>`,
      },
      {
        creatorId: 'hannes',
        content: `<p>Na, noch schnell ein Plakat für den Tag der offenen Tür machen? Aber vorher noch 'n Shot! #UranovRED 😬</p>`,
      },
    ],
    creatorIds: ['bjoern', 'hannes'],
  },
  {
    lat: 41.149071,
    lng: -8.609218,
    title: 'LOBBB',
    description: '<p>Beste Lobsterrolls und Bubbles zu kleine Preisen.</p>',
    creatorIds: ['bjoern'],
    link: 'https://maps.app.goo.gl/caTekS1tGPmMr8Un6',
  },
  {
    lat: 53.95809362101477,
    lng: 10.889774304044188,
    title: 'Bester Drift-Spot',
    description: '<p>Es darf weiterhin nie öffentlich werden, aber man wird keinen besseren Ort finden, um mit einem Golf am Strand zu driften!</p>',
    creatorIds: ['bjoern'],
  },
  {
    lat: 53.557911,
    lng: 9.989434,
    title: 'Uni-Party',
    description:
      '<p>Ey, das waren auch wilde Zeiten. Aber am meisten im Kopf geblieben sind zwei Ereignisse, bin mir gerade nicht sicher, ob die sogar an der gleichen Party passiert sind: Zum einen, wie wir da die Fake-Weihnachtsgeschenke ausgepackt haben und um zum anderen, wie war da auf dem Müllcontainer geklettert sind und der Porsche-Heini uns angepöbelt hat. Legendär.</p>',
    creatorIds: ['bjoern'],
  },
  {
    lat: 50.946605,
    lng: 6.980405,
    title: 'Gamescom?',
    description: `<p>Dann und wann spiele ich ja mit dem Gedanken, dass wir da noch mal hin müssen. Wahrscheinlich mittlerweile viel zu voll, aber das hatte damals einfach was.</p>
      <p>Geile Truppe, lecker Bierchen abends! Du hast bestimmt auch gerade dieses Facebook-Bild dazu im Kopf, wo wir alle mit nem Kölsch in der Hand im Resturant sitzen. Ich hätte schon wieder Bock.</p>`,
    creatorIds: ['bjoern'],
  },
  {
    lat: 52.378517,
    lng: 9.741197,
    title: 'Gestrandet am Hannover ZOB',
    description: `<p>Weißt du noch Hans Zimmer live in Frankfurt? Mega geil. Und dann kam die Rückfahrt im Flixbus. Irgendwo in Hannover musste der Fahrer dann spät abends eine Pause machen und wir haben da am ZOB gehockt. Gerne sprengen!</p>`,
    creatorIds: ['bjoern'],
  },
  {
    lat: 21.521757,
    lng: -77.781167,
    title: '"Tu amigo esta muy loco."',
    description: `<p>Legendärer Urlaub! Leider mit zu kleinem Abfluss im Klo 💩.</p>`,
    creatorIds: ['bjoern'],
  },
  {
    lat: 53.585118,
    lng: 9.974025,
    title: '1. Wohnung alleine',
    description: [
      {
        creatorId: 'bjoern',
        content: `<p>Man sollte vor allem über dieses Badezimmer sprechen! Wenn man da auf Klo war, musste die Tür offen bleiben, weil man mit den Füßen im Flur hing, hahaha.</p>`,
      },
      {
        creatorId: 'hannes',
        content: `<p>Hahaha! Einfach nur ein paar Stichpunkte: Straßenschild, Kontaktlinsenflüssigkeit, Carbonara, Dicke, Psychopath, Fenster etc.</p>`,
      },
    ],
    creatorIds: ['bjoern', 'hannes'],
  },
  {
    lat: 62.99192,
    lng: -31.72515,
    title: `Couldn't resist`,
    creatorIds: ['bjoern'],
  },
  {
    lat: 62.99189,
    lng: -31.72513,
    title: `Couldn't resist`,
    creatorIds: ['bjoern'],
  },
  {
    lat: 62.99186,
    lng: -31.72511,
    title: `Couldn't resist`,
    creatorIds: ['bjoern'],
  },
  {
    lat: 62.99183,
    lng: -31.72511,
    title: `Couldn't resist`,
    creatorIds: ['bjoern'],
  },
  {
    lat: 62.9918,
    lng: -31.72511,
    title: `Couldn't resist`,
    creatorIds: ['bjoern'],
  },
  {
    lat: 62.99179,
    lng: -31.72506,
    title: `Couldn't resist`,
    creatorIds: ['bjoern'],
  },
  {
    lat: 62.99177,
    lng: -31.72503,
    title: `Couldn't resist`,
    creatorIds: ['bjoern'],
  },
  {
    lat: 62.99174,
    lng: -31.72505,
    title: `Couldn't resist`,
    creatorIds: ['bjoern'],
  },
  {
    lat: 62.99173,
    lng: -31.7251,
    title: `Couldn't resist`,
    creatorIds: ['bjoern'],
  },
  {
    lat: 62.99174,
    lng: -31.72516,
    title: `Couldn't resist`,
    creatorIds: ['bjoern'],
  },
  {
    lat: 62.99173,
    lng: -31.72521,
    title: `Couldn't resist`,
    creatorIds: ['bjoern'],
  },
  {
    lat: 62.99175,
    lng: -31.72526,
    title: `Couldn't resist`,
    creatorIds: ['bjoern'],
  },
  {
    lat: 62.99177,
    lng: -31.72529,
    title: `Couldn't resist`,
    creatorIds: ['bjoern'],
  },
  {
    lat: 62.99179,
    lng: -31.72526,
    title: `Couldn't resist`,
    creatorIds: ['bjoern'],
  },
  {
    lat: 62.9918,
    lng: -31.72521,
    title: `Couldn't resist`,
    creatorIds: ['bjoern'],
  },
  {
    lat: 62.99183,
    lng: -31.72521,
    title: `Couldn't resist`,
    creatorIds: ['bjoern'],
  },
  {
    lat: 62.99186,
    lng: -31.72521,
    title: `Couldn't resist`,
    creatorIds: ['bjoern'],
  },
  {
    lat: 62.99189,
    lng: -31.72521,
    title: `Couldn't resist`,
    creatorIds: ['bjoern'],
  },
  {
    lat: 62.99192,
    lng: -31.72519,
    title: `Couldn't resist`,
    creatorIds: ['bjoern'],
  },
  {
    lat: 52.542282,
    lng: 13.420791,
    title: 'Cocktailbar',
    description: '<p>Damit der Abend nicht in die Hose geht, geh ins Höschen.</p>',
    creatorIds: ['britta'],
    link: 'https://maps.app.goo.gl/ajisJfkTQL2hHPda6',
  },
  {
    lat: 48.690689,
    lng: 9.736947,
    title: 'Knödel-Himmel',
    description:
      '<p>Dieses Ungarisch-Österreichische Restaurant bietet Knödel in alles Ausprägungen: süß, herzhaft, Press, Kas, Germ, Topfen, you name it. Einen Abwasch wert, wenn man in der Gegend ist (man kann da nett wandern), lohnt sich aber auch, für das Essen einfach dort hin zu fahren. </p>',
    creatorIds: ['britta'],
    link: 'https://maps.app.goo.gl/bMw7ngMfYkiS8CJH9',
  },
  {
    lat: 47.798772,
    lng: 13.042283,
    title: 'Gurken',
    creatorIds: ['britta'],
  },
  {
    lat: 42.825742,
    lng: 12.132565,
    title: 'Steht auf meiner Hotel-Bucket List',
    creatorIds: ['britta'],
    link: 'https://maps.app.goo.gl/4JmwHrvXFTUJm6oF9',
  },
  {
    lat: 52.488028,
    lng: 13.336813,
    title: 'Unbedingt Königsberger Klopse essen',
    creatorIds: ['britta'],
    link: 'https://maps.app.goo.gl/bXZQz9F532GSgiht6',
  },
  {
    lat: 41.146759,
    lng: -8.677305,
    title: 'Bei starkem Seegang brechen hier die Wellen wunderbar an den Kaimauern',
    creatorIds: ['britta'],
  },
  {
    lat: 38.710914,
    lng: -9.14698,
    title: 'BEST BENEDICT EVER!',
    description: '<p>Egg Benedict auf einem Croissant, mit Garnelen und Krustentier-Hollandaise. Fuck me dead, fuck me sideways!</p>',
    creatorIds: ['britta'],
    link: 'https://maps.app.goo.gl/jr3XnPh9vaFgaNg3A',
  },
  {
    lat: -22.9582001,
    lng: -43.0698415,
    title: 'Praia do Sossego',
    description: '<p>Schöner Stand mit Blick auf den Zuckerhut</p>',
    creatorIds: ['britta'],
  },
  {
    lat: 43.85986,
    lng: 5.511188,
    title: 'Unser wunderschöner Provence Urlaub',
    description: '<p>Rente dort ist gesetzt</p>',
    creatorIds: ['carla'],
  },
  {
    lat: 52.496875,
    lng: 13.364056,
    title: 'Party Carla',
    description: '<p>Beste Schultheisskneipe Berlins</p>',
    creatorIds: ['carla'],
  },
  {
    lat: 52.532547,
    lng: 13.406181,
    title: 'First Date <3 Berlin Edition',
    description: '<p>Ok, wir waren an dem Abend in vielen Lokalitäten, aber das war eins davon. Und es gab dort Maultaschen!</p>',
    creatorIds: ['carla'],
  },
  {
    lat: 48.882361,
    lng: 2.336495,
    title: 'Kleinstes Hotelzimmer der Welt',
    description: '<p>Dank geht raus an Niki</p>',
    creatorIds: ['carla'],
  },
  {
    lat: 47.80533,
    lng: 12.5864,
    title: 'Our happy place',
    description: '<p>Nature-Carla übernimmt</p>',
    creatorIds: ['carla'],
  },
  {
    lat: 55.160428,
    lng: 14.866884,
    title: 'Wedding Family Weekend',
    description: '<p>viele sehr alte Hunde habe ich in Erinnerung. Und Dirk.</p>',
    creatorIds: ['carla'],
  },
  {
    lat: 47.677981,
    lng: 9.173674,
    title: 'Bodensee Zuhause',
    description: '<p>Du bist ja absoluter Local.</p>',
    creatorIds: ['carla'],
  },
  {
    lat: 48.9416,
    lng: -125.546344,
    title: 'Bären-Treff',
    description: '<p>Es war sooo schön dort.</p>',
    creatorIds: ['carla'],
  },
  {
    lat: 50.108197,
    lng: 8.670626,
    title: 'First Date <3 Frankfurt Edition',
    description: '<p>Da habe ich dich untern Tisch getrunken.</p>',
    creatorIds: ['carla'],
    link: 'https://maps.app.goo.gl/YKxRi7NniY2tPgZF6',
  },
  {
    lat: 53.587999,
    lng: 9.982795,
    title: 'Lenhartzstraße 16',
    description: [
      {
        creatorId: 'hannes',
        title: 'Bester Balkon ever!',
        content:
          '<p>Hier ist so viel passiert, Hase! Ein trauriger Moment, als ich damals die Schlüssel wieder abgeben musste, weil du umgezogen bist, aber mir kommen jedes Mal beim Vorbeifahren wieder Erinnerungen hoch! Hauptsächlich an unsere Schaubilder 😏</p>',
      },
      {
        creatorId: 'laura',
        title: 'Sonne, Balkon, Gespräche',
        content: 'Lernsessions für die Ausbildung, Gin Tonic im Glas, Flink haben wir groß gemacht und hatten dabei sehr viel Spaß.',
      },
      {
        creatorId: 'sophia',
        title: 'Dancing Practice',
        content: '<p>Wenn man sich zum tanzen trifft, aber das ganze doch mehr in Drinks und Co endet. Aber getanzt wurde natürlich trotzdem!</p>',
      },
    ],
    creatorIds: ['hannes', 'laura', 'sophia'],
  },
  {
    lat: 53.584428,
    lng: 9.974451,
    title: 'LA CAFFÈTTERIA',
    description: `<p>Endlich mal ne anständige Größe für nen Milchkaffee!</p>`,
    creatorIds: ['hannes'],
    link: 'https://maps.app.goo.gl/L1tcFGxp12NZ45Y59',
  },
  {
    lat: 52.541275,
    lng: 13.408109,
    title: 'Eberswalder Straße',
    description: '<p>Das Eigentliche Berlin, der Rest ist doch nur Umland 😌</p>',
    creatorIds: ['hannes'],
  },
  {
    lat: 53.55592,
    lng: 9.80532,
    title: 'Ponton Blankenese',
    description: '<p>Wir wollten doch einfach nur ein Fischbrötchen essen...😭 ABer manchmal muss man einfach losfahren!</p>',
    creatorIds: ['hannes'],
  },
  {
    lat: 53.613604,
    lng: 9.86115,
    title: 'Heepmann Mansion',
    description: '<p>Junge junge junge... hier haben wir einiges an Hirnkapazität gelassen.. 😅</p>',
    creatorIds: ['hannes'],
  },
  {
    lat: 50.937621,
    lng: 6.962454,
    title: 'Spontaner Ausflug',
    description: '<p>Was für eine Rückfahrt! Was zum Teufel hat Läpple bitte gegessen???</p>',
    creatorIds: ['hannes'],
  },
  {
    lat: 52.518618,
    lng: 13.375171,
    title: '#unangenehm',
    description: '<p>#Nietengate</p>',
    creatorIds: ['hannes'],
  },
  {
    lat: 53.595262,
    lng: 10.041875,
    title: 'Der 4.(!) Stock',
    description:
      '<p>Hier gibt es auch wieder sehr viel zu sagen! War ein sehr gutes Fenster 😊 (und nicht zu vergessen natürlich der Bratschlauch)</p>',
    creatorIds: ['hannes'],
  },
  {
    lat: 53.581533,
    lng: 9.97035,
    title: 'THE BOILERMAN BAR',
    description: '<p>Einfach die besten Negroni, leider geschlossen...</p>',
    creatorIds: ['hannes'],
  },
  {
    lat: 53.641438,
    lng: 9.848379,
    title: 'Home of The Lurch',
    description: [
      {
        creatorId: 'bjoern',
        content: '<p>Oft der Startpunkt userer alljährlichen Weihnachtsspaziergänge mit Glühwein!</p>',
      },
      {
        creatorId: 'hannes',
        content: '<p>Chips, Cola, Diablo 3 🤌🏻</p>',
      },
    ],
    creatorIds: ['bjoern', 'hannes'],
  },
  {
    lat: 52.367573,
    lng: 4.904139,
    title: 'Björns Geburtstag',
    description: '<p>Hier sind wir zum "Live GNTM Finale" gefahren hihi! Aber dieser VPN... (nein, ich halte mich zurück ☝🏻)</p>',
    creatorIds: ['hannes'],
  },
  {
    lat: 54.327101,
    lng: 8.868239,
    title: 'Bendix JGA',
    description: '<p>Keine Ahnung, wo das genau war, aber bitte keine Flips-in-den-Mund-werfen-Challenges mehr mit Seba... BITTE!!!</p>',
    creatorIds: ['hannes'],
  },
  {
    lat: 54.659229,
    lng: 9.929091,
    title: 'Sylvester an der Schlei 😅',
    description: '<p>Einfach spontan ne richtig geile Runde Minecraft gestartet!</p>',
    creatorIds: ['hannes'],
  },
  {
    lat: 41.013493,
    lng: -73.733668,
    title: 'Patrick und Stefan gehen zur Schule',
    description: '<p>Stefan und Patrick gehen zur Schuhe in Amerika und schon ist unsere erste Gemeinsamkeit da!</p>',
    creatorIds: ['laura'],
  },
  {
    lat: 53.556137,
    lng: 9.990604,
    title: 'Statt Adresse Weinladen (Passt schon)',
    description: '<p>Möwe kreischt, Gitarre klingt, auf der Dachterasse die Nacht beginnt.</p>',
    creatorIds: ['laura'],
  },
  {
    lat: 52.56686,
    lng: 13.41451,
    title: 'Hoffentlich nur vorübergehend (Komm zurück)',
    description: '<p>Was ein Glück, ein Balkon ist wieder da! Nur der Blick auf den Lieferwagen bleibt sonderbar!</p>',
    creatorIds: ['laura'],
  },
  {
    lat: 52.522593,
    lng: 13.358921,
    title: 'Zum fröhlichen Zecher',
    description: '<p>Zeche geprellt? Shame on us! Gespartes Geld im Kiosk verprasst!</p>',
    creatorIds: ['laura'],
    link: 'https://maps.app.goo.gl/PZy2qnUtjLSMMJRY9',
  },
  {
    lat: 53.58936,
    lng: 9.979477,
    title: 'Eppendorfer Park',
    description: '<p>Brownies, Picknick am Eppendorfer Baum, der Hund klaut den Schuh? Man glaubt es kaum!</p>',
    creatorIds: ['laura'],
  },
  {
    lat: 53.578496,
    lng: 9.974446,
    title: 'Ufer Restaurant',
    description: '<p>Zwei Freunde gehen essen, könnte das romantisch sein? Nein, denn ein Hund pinkelt ans Stuhlbein!</p>',
    creatorIds: ['laura'],
    link: 'https://maps.app.goo.gl/5ud1MzKS1upjnC5d9',
  },
  {
    lat: 50.088976,
    lng: 14.401552,
    title: 'Mittelalterliche Schänke "U Krále Brabantského"',
    description: [
      {
        creatorId: 'laura',
        title: 'Prag (Patricks B Day)',
        content: 'Prag, Bier, Freunde, es ist Geburtstagszeit, Patrick feiert und wir hauen auf den Tisch vor Heiterkeit.',
      },
      {
        creatorId: 'sophia',
        title: 'Taverne',
        content: '<p>unbegrenzte Getränke, ein königlicher Tisch, Klamauk und Musik, mittelalterliches Gewand! Was braucht man mehr!</p>',
      },
    ],
    creatorIds: ['laura', 'sophia'],
    link: 'https://maps.app.goo.gl/VJMZC1od1aLQDpai8',
  },
  {
    lat: 50.090627,
    lng: 14.418017,
    title: 'Prag (Mein B Day)',
    description: '<p>Schon wieder in Prag, wir feiern bis spät, Patrick erscheint spontan früher, Tattoo-Begleitung steht.</p>',
    creatorIds: ['laura'],
    link: 'https://maps.app.goo.gl/h3UWJGMCb82YxZ6s8',
  },
  {
    lat: 53.58423,
    lng: 9.995667,
    title: 'Bester Bootspot',
    description: [
      {
        creatorId: 'laura',
        content:
          'Auf dem Boot durch Hamburgs Kanälen, war das einzige Wasser unter dem Boot. In den Gläsern war Prosecco und merkwürdigerweise waren wir nie in Seenot.',
      },
      { creatorId: 'sophia', content: '<p>Wie viele tolle Badetage haben wir an diesem Spot verbracht! Einfach nur schön!!</p>' },
    ],
    creatorIds: ['laura', 'sophia'],
  },
  {
    lat: 53.557297,
    lng: 9.954908,
    title: 'Wohlers',
    description: '<p>Ins Wohlers geladen, 30 Jahre ist er jetzt und endlich wird sich mal mit der Familie vernetzt!</p>',
    creatorIds: ['laura'],
    link: 'https://maps.app.goo.gl/wauz6ofgRpHMYmAZ8',
  },
  {
    lat: 53.586304,
    lng: 10.0461,
    title: 'Wanderungen',
    description:
      '<p>Wandern in Hamburgs „Bergen“, mit Essen im Gepäck, Patricks Outfit passte immer zum Zweck! Wasser in der Nähe immer ein Muss, zum Trinken Prosecco ein größerer Genuss. (Wunsch) Wanderungen um Berlin und ein gemeinsamer Wanderurlaub! Nicht viele Meilen, aber viele gute Gespräche</p>',
    creatorIds: ['laura'],
  },
  {
    lat: 53.571667,
    lng: 9.976667,
    title: 'Mathilde',
    description: '<p>Von Hefeweizen zu Whiskey Sour ist vielleicht nicht gesund, ein Brettspiel machte aber noch jeden Abend rund!</p>',
    creatorIds: ['laura'],
    link: 'https://maps.app.goo.gl/fwnppq2cUhFh9JQQ6',
  },
  {
    lat: 53.632369,
    lng: 9.762325,
    title: 'Schon wieder so ein Zufall',
    description: '<p>Schon oft lief er an diesem Grundstück vorbei, erst später erfuhr er, es ist schon wieder eine Gemeinsamkeit dabei!</p>',
    creatorIds: ['laura'],
  },
  {
    lat: 53.56066,
    lng: 10.054771,
    title: 'Pub mit Nerds: Zum tanzenden Einhorn',
    description:
      '<p>(Wunsch für die Zukunft)  Hier möchte ich mit dir, Vera und Hannes bitte einen Pen und Paper Abend planen (Toni will auch mit sagt er gerade)</p>',
    creatorIds: ['laura'],
    link: 'https://maps.app.goo.gl/zZr5gCS1wCcDzTQDA',
  },
  {
    lat: 43.513601,
    lng: 2.989561,
    title: 'Reisetipp Frankreich',
    description: '<p>Super schön gelegen, keine Küche, tolle Gastgeber, was ganz besonderes.</p>',
    creatorIds: ['laura'],
    link: 'https://www.airbnb.de/rooms/9191929?guests=1&adults=1&s=67&unique_share_id=ae563990-9f53-4313-b358-acb36851d7dc',
  },
  {
    lat: 43.540113,
    lng: 12.052127,
    title: 'Reisetipp Italien',
    description: '<p>Mitten in der Natur, Pool, super netter Gastgeber, Präsente aus dem Garten.</p>',
    creatorIds: ['laura'],
    link: 'https://www.airbnb.de/rooms/585297409363688010?guests=1&adults=1&s=67&unique_share_id=fd10b614-f2e6-4135-8058-ee08a9dcf98c',
  },
  {
    lat: 52.894712,
    lng: 13.18599,
    title: 'Reisetipp bei Berlin',
    description: '<p>Sehr süßes Tiny House, günstig, super liebe Gastgeber, zum abschalten.</p>',
    creatorIds: ['laura'],
    link: 'https://www.airbnb.de/rooms/535144110483839881?guests=1&adults=1&s=67&unique_share_id=2161ca76-c739-4343-b081-39540675444f',
  },
  {
    lat: 49.897665,
    lng: 14.846168,
    title: 'Reisetipp Prag',
    description: '<p>Auch sehr cool als Co Working Space, Wanderungen drum herum, tolle Ausstattung.</p>',
    creatorIds: ['laura'],
    link: 'https://www.airbnb.de/rooms/1176189057684465618?guests=1&adults=1&s=67&unique_share_id=10543e48-55fa-42ec-863f-edec538eda8c',
  },
  {
    lat: 47.992417,
    lng: -84.771059,
    title: 'Reisetipp Ontario',
    description: '<p>Super schönes Airbnb in einer wunderschönen Umgebung.</p>',
    creatorIds: ['laura'],
    link: 'https://www.airbnb.de/rooms/51820430?guests=1&adults=1&s=67&unique_share_id=bfd6ca17-a31c-47c6-abf5-0f51ee382df9',
  },
  {
    lat: 45.476545,
    lng: -75.701272,
    title: 'Reisetipp bei Ottawa',
    description: '<p>Tolles Bed and Breakfast, super ruhig gelegen mit Markt direkt vor der Tür.</p>',
    creatorIds: ['laura'],
    link: 'https://www.airbnb.de/rooms/1487904?guests=1&adults=1&s=67&unique_share_id=20bb4ce5-8fef-4f7b-9c69-bb0cce0598da',
  },
  {
    lat: 57.081409,
    lng: -4.054468,
    title: 'Reisetipp Schottland (Festland)',
    description: '<p>Tolle Wandergegend, super liebe Gastgeber.</p>',
    creatorIds: ['laura'],
    link: 'https://www.airbnb.de/rooms/3503698?guests=1&adults=1&s=67&unique_share_id=d4551c63-4a3b-46f6-a2fe-4800a8ae2cdb',
  },
  {
    lat: 59.03629,
    lng: -2.897029,
    title: 'Reisetipp Schottland (Orkney Islands)',
    description: '<p>Super lieber Gastgeber mit viel Wissen über die Umgebung, Bed and Brekfast in denen auch Locals wohnen.</p>',
    creatorIds: ['laura'],
    link: 'https://www.airbnb.de/rooms/42554583?guests=1&adults=1&s=67&unique_share_id=7e46eb5c-13cb-4054-9193-a5d8db77712f',
  },
  {
    lat: 52.364965,
    lng: 13.501047,
    title: 'Flughafen BER',
    description:
      '<p>Der Versuch einer Reise. Wir haben viel, VIEL zu viel Zeit da verbracht. ca 20 Stunden von 24, und dann nicht mal geflogen?! Naja, Fanmeile hat geregelt.</p>',
    creatorIds: ['julia'],
  },
  {
    lat: 43.58334702270839,
    lng: 11.31666460061406,
    title: 'Weingut-AirBnB Notfallplan bei der Florenzreise',
    description: '<p>Manchmal bekommt man vom Leben das, was man wirklich braucht. Auch auf Umwegen. Und mit Wildschweinen.</p>',
    creatorIds: ['julia'],
  },
  {
    lat: 48.28389,
    lng: 8.17408,
    title: 'Robert Gerwig Gymnasium Hausach, die Drachenheimat',
    description: '<p>Gut, noch waren wir nicht da. Aber ein bemerkensweter Teil deiner Arbeit wohnt da.</p>',
    creatorIds: ['julia'],
  },
  {
    lat: 43.544506,
    lng: 11.316422,
    title: 'Antica Macceleria Dario Cecchini',
    description: [
      {
        creatorId: 'julia',
        content: '<p>Bella Cow Cow Cow, Cheers und Mampf. Und ein kleiner Sturz.</p>',
      },
      {
        creatorId: 'sebastian',
        content:
          '<p>Noch nie hat mir jemand liebevoller die Schuhe gebunden. Und dann die Tasse Kaffee an der Bushaltestelle, hach. Und so viel Lebensfreude und Genuss. UND DIE FAGIOLI!!! Nur die Artischocken, naja....</p>',
      },
    ],
    creatorIds: ['julia', 'sebastian'],
    link: 'https://maps.app.goo.gl/ZhnV5uUDRGKTcPeA9',
  },
  {
    lat: 52.518506,
    lng: 13.386176,
    title: 'Windhorst',
    description: '<p>Herrengedeck, Maillard und Stunden an Gesprächen</p>',
    creatorIds: ['julia'],
    link: 'https://maps.app.goo.gl/ceVeeVAvtmoR5pDF6',
  },
  {
    lat: 52.5177,
    lng: 13.378011,
    title: 'Deutscher Bundestag',
    description: '<p>Wörk, wörk, wörk. Und auf meine Krone für die beste Patin ever warte ich bis heute...</p>',
    creatorIds: ['julia'],
  },
  {
    lat: 52.517817,
    lng: 13.380273,
    title: 'ButterLindner',
    description: '<p>Zwei Flaschen wie immer? Und Becher dazu, wissen wir doch...</p>',
    creatorIds: ['julia'],
    link: 'https://maps.app.goo.gl/kiAfgvS6iUmk8Udw9',
  },
  {
    lat: 52.496461,
    lng: 13.420877,
    title: 'Restaurant Horvath',
    description: '<p>Sellerie-Sekt kann wirklich geil sein. Und alles andere eh</p>',
    creatorIds: ['julia'],
    link: 'https://maps.app.goo.gl/zfWATpKWjbicVu4f9',
  },
  {
    lat: 52.451442,
    lng: 13.334748,
    title: 'Tanzschule Daniel Stelter',
    description: '<p>Dänzi und griechischer Wein</p>',
    creatorIds: ['julia'],
    link: 'https://maps.app.goo.gl/s26FsCf6qcSt1Xnx6',
  },
  {
    lat: 43.216667,
    lng: 2.35,
    title: 'Carcasonne',
    description: [
      {
        creatorId: 'julia',
        content: '<p>ICH HAB DIE WIESE GECLAIMED!</p>',
      },
      {
        creatorId: 'sebastian',
        content:
          '<p>Während Eure Durschlauchtheit lieber mit Julia auf den Wiesen chillt, versuch ich krampfhaft und planlos auch mal zu gewinnen.</p>',
      },
    ],
    creatorIds: ['julia', 'sebastian'],
  },
  {
    lat: 53.546994,
    lng: 9.932798,
    title: 'Christianskirche',
    description:
      '<p>Spontanideen bei Alkohol sind die besten Ideen. Und resultieren im Kurzausflug nach Hamburg - vom Fallen und Steigen, mit ganz viel Träumen und Musik</p>',
    creatorIds: ['julia'],
  },
  {
    lat: 52.499107,
    lng: 13.479626,
    title: 'Der schönste Ausblick Berlins',
    description: '<p>So viele Erinnerungen, wie ich geputzt habe, nachdem du gekocht hast. Und Geoguessr.</p>',
    creatorIds: ['sebastian'],
  },
  {
    lat: 52.554335,
    lng: 13.52053,
    title: 'Kamprathhaus',
    description: '<p>Herstellungsort DES Sommergetränks seit 2023 - der legendäre Gurkenlikör.</p>',
    creatorIds: ['sebastian'],
  },
  {
    lat: 53.549167,
    lng: 9.950751,
    title: 'First "Dance"',
    description:
      '<p>19.08.2020 Wilde Wladi Welt - er kommt rein und fängt an zu tanzen. Tja dann mal los! (Wir haben im Gemeindehaus der Kirche/ Capello Altona getanzt! Dieses wurde aber leider abgerissen.) Aber die Erinnerung bleibt!</p>',
    creatorIds: ['sophia'],
  },
  {
    lat: 53.546847,
    lng: 9.972271,
    title: 'Film Fun JUKZ',
    description: '<p>Teil des Films Teil der Crew</p>',
    creatorIds: ['sophia'],
  },
  {
    lat: 48.20362,
    lng: 16.397018,
    title: 'Vienna Calling',
    description: '<p>31.12.2022 Silvester im Hause Geroooonimo</p>',
    creatorIds: ['sophia'],
  },
  {
    lat: 53.971201,
    lng: 14.142713,
    title: 'Sonneninsel Villa',
    description: '<p>Usedooom mit den üblichen verdächtigen in meiner Privatvilla und Kaviar zum Frühstück</p>',
    creatorIds: ['sophia'],
  },
  {
    lat: 53.557878,
    lng: 9.989566,
    title: 'DrinksDrinksDrinks',
    description: '<p>random Abend mit random Leuten fängt im Tipsy Baker an und gipfelt auf deiner Dachterrasse in den Colonnaden!</p>',
    creatorIds: ['sophia'],
    link: 'https://maps.app.goo.gl/o75Wg6sNAqeFu816A',
  },
  {
    lat: 52.530321,
    lng: 13.385295,
    title: 'Jazzzz',
    description: '<p>Wunderschöner und entspannter Überaschungsgeburtstag mit neuem goldenem Mantel! Nochmal Danke für die schöne Idee <3</p>',
    creatorIds: ['sophia'],
  },
  {
    lat: 48.157551,
    lng: 11.64461,
    title: 'Sophia Hometown',
    description: '<p>Hier war ich zwar nicht dabei, aber damit du die Adresse nicht verlierst! Du bist immer willkommen! ;)</p>',
    creatorIds: ['sophia'],
  },
  {
    lat: 39.323523,
    lng: 2.985477,
    title: 'Styler-Musik-Hotel',
    description:
      '<p>Must Be: Coolstes Hotel in dem ich bis jetzt gewesen bin! Und sooo cool und stylisch mit super Musik! Clueso hat sogar sein eigenes Studio hier!</p>',
    creatorIds: ['sophia'],
    link: 'https://maps.app.goo.gl/ac7rspProwD2VRjBA',
  },
  {
    lat: 48.196841,
    lng: 16.365336,
    title: 'Kultkino & Bar',
    description: '<p>Must Be: Tolles Kino und noch coolere Bar!</p>',
    creatorIds: ['sophia'],
    link: 'https://maps.app.goo.gl/SKSkNFYMTtTwKpod9',
  },
  {
    lat: 40.704871,
    lng: 19.949435,
    title: 'Food Albanien',
    description:
      '<p>Wenn du in Berat bist musst du unbedingt zu Lilli! Unvergesslicher Abend mit mega Essen! Aber am besten sehr früh reservieren. Es haben nur 12 Leute "bei ihm zuhause" Platz. +335692349362</p>',
    creatorIds: ['sophia'],
  },
  {
    lat: 52.544082,
    lng: 13.369342,
    title: 'Kneipe zum saufen: Zum Magendoktor',
    description:
      '<p>Schön asoziale Kneipe, bisschen Hipster geworden aber durchaus nicht ohne, große Chance Marius zu treffen, Spitzname Mausius</p>',
    link: 'https://maps.app.goo.gl/sWJfHEeoFmTResZt9',
    creatorIds: ['toni'],
  },
  {
    lat: 52.540919,
    lng: 13.414197,
    title: 'Gaststättenempfehlung: Zum Schusterjungen',
    description: '<p>Kleine Karte, deutsche Küche, super geil, zwar Franchise aber trotzdem gut</p>',
    link: 'https://maps.app.goo.gl/2MsfcUyVutR2nhUH7',
    creatorIds: ['toni'],
  },
  {
    lat: 52.539912,
    lng: 13.414703,
    title: 'Kneipe mit guter Musik: The Doors',
    description: '<p>Musst das Ananasbier trinken, ich finde es zwar ecklig aber man muss es probiert haben, Off Rock Musikkneipe</p>',
    creatorIds: ['toni'],
    link: 'https://maps.app.goo.gl/ikPXEyna4PTmb3o86',
  },
  {
    lat: 52.507222,
    lng: 13.46527,
    title: 'Zum Frühstücken: Alte Turnhalle',
    description: '<p>Zum Frühstück topp, großartig, bissl laut, im Sommer draußen sitzen, auf jeden Fall reservieren!</p>',
    creatorIds: ['toni'],
    link: 'https://maps.app.goo.gl/EVdhVwg6o72Qgqns9',
  },
  {
    lat: 52.510691,
    lng: 13.456262,
    title: 'Bester Gemüsedöner: Dach Döner',
    description: '<p>Gibt ja in Berlin den berühmten Mustafa GemüseDöner, hier gibts den genauso, ohne anstehen!</p>',
    creatorIds: ['toni'],
    link: 'https://maps.app.goo.gl/4aK4S9ACsD7dUPy18',
  },
  {
    lat: 52.498227,
    lng: 13.385409,
    title: 'Grieche mit veganen Optionen: Taverna Athene',
    description: '<p>Ist ja beim Griechen eher ungewöhnlich, gibt auch Fleisch, lohnt sich!</p>',
    creatorIds: ['toni'],
    link: 'https://maps.app.goo.gl/oXQqvJufngxz7tKw9',
  },
  {
    lat: 52.499641,
    lng: 13.424949,
    title: 'Bester Inder: Amrit',
    description: '<p>Steht zwar Cocktail dran aber übelst guter Inder, guter Preis!</p>',
    creatorIds: ['toni'],
    link: 'https://maps.app.goo.gl/pn5HbsCURmBYd3p19',
  },
  {
    lat: 52.502072,
    lng: 13.420221,
    title: 'Gute Punkrockkneipe: Trinkteufel',
    description: '<p>Muss man gewesen sein, Klassiker, Punkkneipe die immer noch überlebt</p>',
    creatorIds: ['toni'],
    link: 'https://maps.app.goo.gl/9PywtLtM9FWwLxoy5',
  },
  {
    lat: 52.510417,
    lng: 13.454049,
    title: 'Guter Brettspielladen zum Spiele testen',
    description: '<p>Kann man kaufen, kann man ausleihen, kann man vor Ort spielen</p>',
    creatorIds: ['toni'],
    link: 'https://maps.app.goo.gl/bGnB8zKucS7TxbGH6',
  },
  {
    lat: 53.463494,
    lng: 9.980461,
    title: 'Pub mit Livemusik: The old dubliner',
    description:
      '<p>(Wunsch für die Zukunft) Hier hatten Toni und Laura ihr erstes Date und würden dich hier auch gerne mal einladen! Aber keine Gläser schmeißen! "Ich habe 11 mal Hausverbot oder so"</p>',
    creatorIds: ['toni'],
    link: 'https://maps.app.goo.gl/ssJcVHV5YTmh6r4W6',
  },
];
